name: 💡 Feature Request
description: Suggest an idea or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! 🦞
        
        **Tip:** For bigger ideas, consider starting a Discussion first to gather feedback.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or pain point
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
      placeholder: I also considered...

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Channels (Telegram/Discord/Slack)
        - Tools
        - Sub-agents
        - Team/Permissions
        - Scheduler
        - Memory/Knowledge
        - Providers (Anthropic/OpenAI)
        - CLI
        - Documentation
        - Other
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to work on this?
      options:
        - label: I'd be interested in submitting a PR for this
